version: '3.9'

services:
    bab-db:
        image: postgres
        container_name: bab-db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - bab-data:/var/lib/postgresql/data

volumes:
    bab-data:
