// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    account_id,
    amount
) VALUES ( 
    $1, $2
)
RETURNING id, created_at, account_id, amount
`

type CreateEntryParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.queryRow(ctx, q.createEntryStmt, createEntry, arg.AccountID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AccountID,
		&i.Amount,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, created_at, account_id, amount FROM entries
WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, accountID int64) (Entry, error) {
	row := q.queryRow(ctx, q.getEntryStmt, getEntry, accountID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AccountID,
		&i.Amount,
	)
	return i, err
}
