name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        db:
            image: postgres
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: secret
                POSTGRES_DB: bab
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    steps:
    - uses: actions/checkout@v3

    - name: Install Go migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.darwin-amd64.tar.gz | tar xvz
        sudo mv ./migrate /usr/local/bin/migrate
        which migrate

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: make test
